add_newline = false

[line_break]
disabled = true

[character]
success_symbol = ""
error_symbol = ""

[package]
disabled = true

[nodejs]
disabled = true

[battery]
disabled = true

[directory]
truncation_length = 1
