add_newline = false
[character]
success_symbol = "[](bold blue)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"
[package]
disabled = true
[conda]
disabled = true
[java]
disabled = true
[lua]
disabled = true
[nodejs]
disabled = true
