add_newline = false
[line_break]
disabled = true
[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold green)"
[package]
disabled = true
[nodejs]
disabled = true
